# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Artist(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, artist_id: str=None, artist_name: str=None):  # noqa: E501
        """Artist - a model defined in Swagger

        :param artist_id: The artist_id of this Artist.  # noqa: E501
        :type artist_id: str
        :param artist_name: The artist_name of this Artist.  # noqa: E501
        :type artist_name: str
        """
        self.swagger_types = {
            'artist_id': str,
            'artist_name': str
        }

        self.attribute_map = {
            'artist_id': 'ArtistID',
            'artist_name': 'ArtistName'
        }

        self._artist_id = artist_id
        self._artist_name = artist_name

    @classmethod
    def from_dict(cls, dikt) -> 'Artist':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The artist of this Artist.  # noqa: E501
        :rtype: Artist
        """
        return util.deserialize_model(dikt, cls)

    @property
    def artist_id(self) -> str:
        """Gets the artist_id of this Artist.


        :return: The artist_id of this Artist.
        :rtype: str
        """
        return self._artist_id

    @artist_id.setter
    def artist_id(self, artist_id: str):
        """Sets the artist_id of this Artist.


        :param artist_id: The artist_id of this Artist.
        :type artist_id: str
        """

        self._artist_id = artist_id

    @property
    def artist_name(self) -> str:
        """Gets the artist_name of this Artist.


        :return: The artist_name of this Artist.
        :rtype: str
        """
        return self._artist_name

    @artist_name.setter
    def artist_name(self, artist_name: str):
        """Sets the artist_name of this Artist.


        :param artist_name: The artist_name of this Artist.
        :type artist_name: str
        """

        self._artist_name = artist_name
